version: "0.5"

# Works for DEV, CI, and USERS
# - ensure: downloads binary if missing
# - on_failure restart + file_watch for hot reload

processes:
  arc:
    command: task arc:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /health
      initial_delay_seconds: 3
      period_seconds: 5

  grafana:
    command: task grafana:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 3000
        path: /api/health
      initial_delay_seconds: 5
      period_seconds: 5

  liftbridge:
    command: task liftbridge:run
    working_dir: .
    depends_on:
      nats:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: nc -z localhost 9292
      initial_delay_seconds: 3
      period_seconds: 5

  nats:
    command: task nats:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8222
        path: /healthz
      initial_delay_seconds: 2
      period_seconds: 5

  telegraf:
    command: task telegraf:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      liftbridge:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
