version: "0.5"

# Works for DEV, CI, and USERS with hot reload
# - DEV: edit code, run `task build`, PC auto-restarts
# - USER: run `task bin:download`, PC auto-restarts
# - ensure task downloads binary if missing

processes:
  arc:
    command: task arc:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /health
      initial_delay_seconds: 3
      period_seconds: 5
    depends_on:
      arc-watch:
        condition: process_started

  arc-watch:
    command: sleep infinity
    working_dir: .
    restart: watch
    watch:
      - arc/.bin/arc

  grafana:
    command: task grafana:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      grafana-watch:
        condition: process_started
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 3000
        path: /api/health
      initial_delay_seconds: 5
      period_seconds: 5

  grafana-watch:
    command: sleep infinity
    working_dir: .
    restart: watch
    watch:
      - grafana/.bin/bin/grafana-server

  liftbridge:
    command: task liftbridge:run
    working_dir: .
    depends_on:
      nats:
        condition: process_healthy
      liftbridge-watch:
        condition: process_started
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: nc -z localhost 9292
      initial_delay_seconds: 3
      period_seconds: 5

  liftbridge-watch:
    command: sleep infinity
    working_dir: .
    restart: watch
    watch:
      - liftbridge/.bin/liftbridge

  nats:
    command: task nats:run
    working_dir: .
    depends_on:
      nats-watch:
        condition: process_started
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8222
        path: /healthz
      initial_delay_seconds: 2
      period_seconds: 5

  nats-watch:
    command: sleep infinity
    working_dir: .
    restart: watch
    watch:
      - nats/.bin/nats-server

  telegraf:
    command: task telegraf:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      liftbridge:
        condition: process_healthy
      telegraf-watch:
        condition: process_started
    availability:
      restart: on_failure
      backoff_seconds: 5

  telegraf-watch:
    command: sleep infinity
    working_dir: .
    restart: watch
    watch:
      - telegraf/.bin/telegraf
