version: "0.5"

# Works for DEV, CI, and USERS - just runs binaries directly
# Pre-requisite: run `task bin:build` (dev) or `task bin:download` (user) first

processes:
  arc:
    command: ./arc/.bin/arc --config arc/arc.toml
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /health
      initial_delay_seconds: 3
      period_seconds: 5

  grafana:
    command: ./grafana/.bin/bin/grafana-server --homepath=./grafana/.bin --config=./grafana/grafana.ini cfg:default.paths.data=./grafana/.data cfg:default.paths.plugins=./grafana/.data/plugins cfg:default.paths.provisioning=./grafana/.data/provisioning
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 3000
        path: /api/health
      initial_delay_seconds: 5
      period_seconds: 5

  liftbridge:
    command: ./liftbridge/.bin/liftbridge --data-dir=./liftbridge/.data
    working_dir: .
    depends_on:
      nats:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: nc -z localhost 9292
      initial_delay_seconds: 3
      period_seconds: 5

  nats:
    command: ./nats/.bin/nats-server --config nats/nats.conf
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8222
        path: /healthz
      initial_delay_seconds: 2
      period_seconds: 5

  telegraf:
    command: ./telegraf/.bin/telegraf --config telegraf/telegraf.conf
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      liftbridge:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
