version: "0.5"

# Works for DEV, CI, and USERS
# - ensure: downloads binary if missing
# - watch: auto-restart when binary changes (dev builds, user downloads)

processes:
  arc:
    command: task arc:run
    working_dir: .
    availability:
      restart: watch
    file_watch:
      - arc/.bin/arc
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8000
        path: /health
      initial_delay_seconds: 3
      period_seconds: 5

  grafana:
    command: task grafana:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
    availability:
      restart: watch
    file_watch:
      - grafana/.bin/bin/grafana-server
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 3000
        path: /api/health
      initial_delay_seconds: 5
      period_seconds: 5

  liftbridge:
    command: task liftbridge:run
    working_dir: .
    depends_on:
      nats:
        condition: process_healthy
    availability:
      restart: watch
    file_watch:
      - liftbridge/.bin/liftbridge
    readiness_probe:
      exec:
        command: nc -z localhost 9292
      initial_delay_seconds: 3
      period_seconds: 5

  nats:
    command: task nats:run
    working_dir: .
    availability:
      restart: watch
    file_watch:
      - nats/.bin/nats-server
    readiness_probe:
      http_get:
        host: 127.0.0.1
        port: 8222
        path: /healthz
      initial_delay_seconds: 2
      period_seconds: 5

  telegraf:
    command: task telegraf:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      liftbridge:
        condition: process_healthy
    availability:
      restart: watch
    file_watch:
      - telegraf/.bin/telegraf
