version: "0.5"

# Delegate all implementation details to subsystem Taskfiles
# Process Compose only orchestrates: process dependencies and restart policies
# Commands call task <subsystem>:run (execute binary), probes call task <subsystem>:health (returns immediately)

processes:
  arc:
    command: task arc:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task arc:health
      initial_delay_seconds: 3
      period_seconds: 5


  hugo:
    command: task docs:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task docs:health
      initial_delay_seconds: 5
      period_seconds: 5

  liftbridge:
    command: task liftbridge:run
    working_dir: .
    depends_on:
      nats:
        condition: process_healthy
    shutdown:
      timeout_seconds: 5
    availability:
      restart: on_failure
      backoff_seconds: 3
    readiness_probe:
      exec:
        command: task liftbridge:health
      initial_delay_seconds: 3
      period_seconds: 5

  nats:
    command: task nats:run
    working_dir: .
    shutdown:
      timeout_seconds: 5
    availability:
      restart: on_failure
      backoff_seconds: 3
    readiness_probe:
      exec:
        command: task nats:health
      initial_delay_seconds: 2
      period_seconds: 5

  sync:
    command: task sync:run
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task sync:health
      initial_delay_seconds: 3
      period_seconds: 10

  sync-poller:
    command: task sync:poll
    working_dir: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task sync:health:poller
      initial_delay_seconds: 3
      period_seconds: 30

  sync-taskfile-poller:
    command: task sync:poll:taskfiles
    working_dir: .
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task sync:health:poller
      initial_delay_seconds: 3
      period_seconds: 30

  telegraf:
    command: task telegraf:run
    working_dir: .
    depends_on:
      arc:
        condition: process_healthy
      liftbridge:
        condition: process_healthy
    availability:
      restart: on_failure
      backoff_seconds: 5
    readiness_probe:
      exec:
        command: task telegraf:health
      initial_delay_seconds: 3
      period_seconds: 5
