version: '3'

vars:
  RELEASE_REPO: joeblew999/plat-telemetry
  RELEASE_VERSION: latest

includes:
  nats: ./nats
  liftbridge: ./liftbridge
  arc: ./arc
  telegraf: ./telegraf
  grafana: ./grafana
  docs: ./docs

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  src:clone:
    desc: Clone all subsystem repositories (parallel)
    deps:
      - nats:src:clone
      - liftbridge:src:clone
      - arc:src:clone
      - telegraf:src:clone
      - grafana:src:clone

  src:update:
    desc: Update all subsystem repositories
    cmds:
      - task nats:src:update
      - task liftbridge:src:update
      - task arc:src:update
      - task telegraf:src:update
      - task grafana:src:update

  bin:build:
    desc: Build all subsystems from source (parallel)
    deps:
      - nats:build
      - liftbridge:build
      - arc:build
      - telegraf:build
      - grafana:build

  "bin:build:one":
    desc: "Build a single subsystem (usage: task bin:build:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:build

  "bin:download:one":
    desc: "Download a single subsystem binary (usage: task bin:download:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:bin:download

  "src:clone:one":
    desc: "Clone a single subsystem source (usage: task src:clone:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:src:clone

  bin:download:
    desc: Download pre-built binaries from release (parallel, for users)
    deps:
      - nats:bin:download
      - liftbridge:bin:download
      - arc:bin:download
      - telegraf:bin:download
      - grafana:bin:download

  run:
    desc: Run all services with Process Compose
    cmds:
      - process-compose up -U -u ./.pc.sock

  run:fg:
    desc: Run all services in foreground (no TUI)
    cmds:
      - process-compose up -U -u ./.pc.sock -t=false

  run:attach:
    desc: Attach to running Process Compose instance
    cmds:
      - process-compose attach -U -u ./.pc.sock

  stop:
    desc: Stop all services
    cmds:
      - process-compose down -U -u ./.pc.sock

  test:
    desc: Run tests for all subsystems
    cmds:
      - task nats:test
      - task liftbridge:test
      - task arc:test
      - task telegraf:test

  deps:
    desc: Download dependencies for all subsystems
    cmds:
      - task nats:deps
      - task liftbridge:deps
      - task arc:deps
      - task telegraf:deps

  clean:
    desc: Clean all build artifacts
    cmds:
      - task nats:clean
      - task liftbridge:clean
      - task arc:clean
      - task telegraf:clean
      - task grafana:clean

  clean:data:
    desc: Clean all data directories
    cmds:
      - task nats:clean:data
      - task liftbridge:clean:data
      - task arc:clean:data
      - task telegraf:clean:data
      - task grafana:clean:data

  clean:src:
    desc: Clean all source directories
    cmds:
      - task nats:clean:src
      - task liftbridge:clean:src
      - task arc:clean:src
      - task telegraf:clean:src
      - task grafana:clean:src

  clean:all:
    desc: Clean everything (.src, .bin, .data)
    cmds:
      - task nats:clean:all
      - task liftbridge:clean:all
      - task arc:clean:all
      - task telegraf:clean:all
      - task grafana:clean:all

  install:deps:
    desc: Install required tools (hugo, gh, process-compose)
    cmds:
      - |
        if ! command -v hugo &> /dev/null; then
          echo "Installing hugo..."
          {{if eq OS "darwin"}}brew install hugo{{else}}go install github.com/gohugoio/hugo@latest{{end}}
        fi
      - |
        if ! command -v gh &> /dev/null; then
          echo "Installing gh..."
          {{if eq OS "darwin"}}brew install gh{{else}}go install github.com/cli/cli/v2/cmd/gh@latest{{end}}
        fi
      - |
        if ! command -v process-compose &> /dev/null; then
          echo "Installing process-compose..."
          {{if eq OS "darwin"}}brew install process-compose{{else}}go install github.com/F1bonacc1/process-compose@latest{{end}}
        fi
    status:
      - command -v hugo
      - command -v gh
      - command -v process-compose


  manifest:
    desc: Show pinned versions vs installed versions
    cmds:
      - |
        echo "=== Subsystem Versions ==="
        echo ""
        echo "SUBSYSTEM     PINNED       SOURCE            BINARY"
        echo "---------     ------       ------            ------"
        echo "nats          {{.NATS_VERSION | default "v2.10.24"}}    $([ -d nats/.src/.git ] && git -C nats/.src describe --tags 2>/dev/null || echo '-')    $(cat nats/.bin/.version 2>/dev/null || echo '-')"
        echo "liftbridge    {{.LB_VERSION | default "v1.10.0"}}     $([ -d liftbridge/.src/.git ] && git -C liftbridge/.src describe --tags 2>/dev/null || echo '-')     $(cat liftbridge/.bin/.version 2>/dev/null || echo '-')"
        echo "arc           {{.ARC_VERSION | default "main"}}         $([ -d arc/.src/.git ] && git -C arc/.src rev-parse --short HEAD 2>/dev/null || echo '-')         $(cat arc/.bin/.version 2>/dev/null || echo '-')"
        echo "telegraf      {{.TG_VERSION | default "master"}}       $([ -d telegraf/.src/.git ] && git -C telegraf/.src rev-parse --short HEAD 2>/dev/null || echo '-')       $(cat telegraf/.bin/.version 2>/dev/null || echo '-')"
        echo "grafana       {{.GF_VERSION | default "11.4.0"}}      $(cat grafana/.bin/.version 2>/dev/null || echo '-')          $(cat grafana/.bin/.version 2>/dev/null || echo '-')"

  github:pages:
    desc: Enable GitHub Pages (idempotent)
    cmds:
      - |
        if gh api repos/{{.RELEASE_REPO}}/pages 2>/dev/null | grep -q '"build_type":"workflow"'; then
          echo "GitHub Pages already enabled with Actions"
        else
          echo "Enabling GitHub Pages..."
          gh api repos/{{.RELEASE_REPO}}/pages -X POST -f build_type=workflow 2>/dev/null || \
          gh api repos/{{.RELEASE_REPO}}/pages -X PUT -f build_type=workflow
        fi
    status:
      - gh api repos/{{.RELEASE_REPO}}/pages 2>/dev/null | grep -q '"build_type":"workflow"'
