version: '3'

vars:
  RELEASE_REPO: joeblew999/plat-telemetry
  RELEASE_VERSION: latest
  DIST_DIR: '{{.ROOT_DIR}}/.dist'

includes:
  arc: ./arc
  docs: ./docs
  gh: ./gh
  grafana: ./grafana
  liftbridge: ./liftbridge
  nats: ./nats
  pc: ./pc
  telegraf: ./telegraf

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  src:clone:
    desc: Clone all subsystem repositories (parallel)
    deps:
      - arc:src:clone
      - docs:src:clone
      - gh:src:clone
      - grafana:src:clone
      - liftbridge:src:clone
      - nats:src:clone
      - pc:src:clone
      - telegraf:src:clone

  src:update:
    desc: Update all subsystem repositories
    cmds:
      - task arc:src:update
      - task docs:src:update
      - task gh:src:update
      - task grafana:src:update
      - task liftbridge:src:update
      - task nats:src:update
      - task pc:src:update
      - task telegraf:src:update

  bin:build:
    desc: Build all subsystems from source (parallel)
    deps:
      - arc:bin:build
      - docs:bin:build
      - gh:bin:build
      - grafana:bin:build
      - liftbridge:bin:build
      - nats:bin:build
      - pc:bin:build
      - telegraf:bin:build

  "bin:build:one":
    desc: "Build a single subsystem (usage: task bin:build:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:bin:build

  "bin:download:one":
    desc: "Download a single subsystem binary (usage: task bin:download:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:bin:download

  "src:clone:one":
    desc: "Clone a single subsystem source (usage: task src:clone:one SUBSYSTEM=nats)"
    vars:
      SUBSYSTEM: '{{.SUBSYSTEM | default "nats"}}'
    cmds:
      - task {{.SUBSYSTEM}}:src:clone

  bin:download:
    desc: Download pre-built binaries from release (parallel, for users)
    deps:
      - arc:bin:download
      - docs:bin:download
      - gh:bin:download
      - grafana:bin:download
      - liftbridge:bin:download
      - nats:bin:download
      - pc:bin:download
      - telegraf:bin:download

  logs:
    desc: "Tail logs for a process (usage: task logs PROC=nats)"
    cmds:
      - task pc:logs PROC={{.PROC}}

  start:
    desc: Start all services with Process Compose
    cmds:
      - task pc:run

  start:attach:
    desc: Attach to running Process Compose instance (requires real TTY)
    cmds:
      - task pc:attach

  start:fg:
    desc: Start all services in foreground (no TUI)
    cmds:
      - task pc:run:fg

  status:
    desc: Show status of all processes
    cmds:
      - task pc:status

  stop:
    desc: Stop all services
    cmds:
      - task pc:stop

  test:
    desc: Run tests for all subsystems
    cmds:
      - task arc:test
      - task docs:test
      - task gh:test
      - task liftbridge:test
      - task nats:test
      - task pc:test
      - task telegraf:test

  deps:
    desc: Download dependencies for all subsystems
    cmds:
      - task arc:deps
      - task docs:deps
      - task gh:deps
      - task liftbridge:deps
      - task nats:deps
      - task pc:deps
      - task telegraf:deps

  clean:
    desc: Clean all build artifacts
    cmds:
      - task arc:clean
      - task gh:clean
      - task grafana:clean
      - task liftbridge:clean
      - task nats:clean
      - task pc:clean
      - task telegraf:clean

  clean:data:
    desc: Clean all data directories
    cmds:
      - task arc:clean:data
      - task gh:clean:data
      - task grafana:clean:data
      - task liftbridge:clean:data
      - task nats:clean:data
      - task pc:clean:data
      - task telegraf:clean:data

  clean:src:
    desc: Clean all source directories
    cmds:
      - task arc:clean:src
      - task gh:clean:src
      - task grafana:clean:src
      - task liftbridge:clean:src
      - task nats:clean:src
      - task pc:clean:src
      - task telegraf:clean:src

  clean:all:
    desc: Clean everything (.src, .bin, .data)
    cmds:
      - task arc:clean:all
      - task gh:clean:all
      - task grafana:clean:all
      - task liftbridge:clean:all
      - task nats:clean:all
      - task pc:clean:all
      - task telegraf:clean:all

  package:
    desc: Package all binaries for release (parallel)
    vars:
      GOOS: '{{.GOOS | default OS}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
      DIST: '{{.DIST | default .DIST_DIR}}'
    cmds:
      - mkdir -p {{.DIST}}
      - for: [arc, gh, grafana, liftbridge, nats, pc, telegraf]
        task: '{{.ITEM}}:package'
        vars:
          GOOS: '{{.GOOS}}'
          GOARCH: '{{.GOARCH}}'
          DIST: '{{.DIST}}'

  # CI-specific tasks
  ci:dist:
    desc: Output the DIST_DIR for CI to use
    cmds:
      - echo "{{.DIST_DIR}}"
    silent: true



  install:deps:
    desc: Install required tools (hugo, gh, process-compose)
    cmds:
      - task docs:ensure
      - task gh:ensure
      - task pc:ensure
    status:
      - command -v hugo
      - test -f gh/.bin/gh
      - command -v process-compose


  manifest:
    desc: Show pinned versions vs installed versions
    cmds:
      - |
        echo "=== Subsystem Versions ==="
        echo ""
        echo "SUBSYSTEM     PINNED       SOURCE            BINARY"
        echo "---------     ------       ------            ------"
        echo "nats          {{.NATS_VERSION | default "v2.10.24"}}    $([ -d nats/.src/.git ] && git -C nats/.src describe --tags 2>/dev/null || echo '-')    $(cat nats/.bin/.version 2>/dev/null || echo '-')"
        echo "liftbridge    {{.LB_VERSION | default "v1.10.0"}}     $([ -d liftbridge/.src/.git ] && git -C liftbridge/.src describe --tags 2>/dev/null || echo '-')     $(cat liftbridge/.bin/.version 2>/dev/null || echo '-')"
        echo "arc           {{.ARC_VERSION | default "main"}}         $([ -d arc/.src/.git ] && git -C arc/.src rev-parse --short HEAD 2>/dev/null || echo '-')         $(cat arc/.bin/.version 2>/dev/null || echo '-')"
        echo "telegraf      {{.TG_VERSION | default "master"}}       $([ -d telegraf/.src/.git ] && git -C telegraf/.src rev-parse --short HEAD 2>/dev/null || echo '-')       $(cat telegraf/.bin/.version 2>/dev/null || echo '-')"
        echo "grafana       {{.GF_VERSION | default "11.4.0"}}      $(cat grafana/.bin/.version 2>/dev/null || echo '-')          $(cat grafana/.bin/.version 2>/dev/null || echo '-')"

  github:pages:
    desc: Enable GitHub Pages (idempotent)
    deps: [gh:ensure]
    cmds:
      - |
        if gh/.bin/gh api repos/{{.RELEASE_REPO}}/pages 2>/dev/null | grep -q '"build_type":"workflow"'; then
          echo "GitHub Pages already enabled with Actions"
        else
          echo "Enabling GitHub Pages..."
          gh/.bin/gh api repos/{{.RELEASE_REPO}}/pages -X POST -f build_type=workflow 2>/dev/null || \
          gh/.bin/gh api repos/{{.RELEASE_REPO}}/pages -X PUT -f build_type=workflow
        fi
    status:
      - gh/.bin/gh api repos/{{.RELEASE_REPO}}/pages 2>/dev/null | grep -q '"build_type":"workflow"'
