version: '3'

vars:
  RELEASE_REPO: joeblew999/plat-telemetry
  RELEASE_VERSION: latest

includes:
  nats: ./nats
  liftbridge: ./liftbridge
  arc: ./arc
  telegraf: ./telegraf
  grafana: ./grafana

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  src:clone:
    desc: Clone all subsystem repositories
    cmds:
      - task nats:src:clone
      - task liftbridge:src:clone
      - task arc:src:clone
      - task telegraf:src:clone
      - task grafana:src:clone

  src:update:
    desc: Update all subsystem repositories
    cmds:
      - task nats:src:update
      - task liftbridge:src:update
      - task arc:src:update
      - task telegraf:src:update
      - task grafana:src:update

  build:
    desc: Build all subsystems
    cmds:
      - task nats:build
      - task liftbridge:build
      - task arc:build
      - task telegraf:build
      - task grafana:build

  bin:download:
    desc: Download pre-built binaries from release (for users)
    cmds:
      - task nats:bin:download
      - task liftbridge:bin:download
      - task arc:bin:download
      - task telegraf:bin:download
      - task grafana:src:clone

  run:
    desc: Run all services with Process Compose
    cmds:
      - process-compose up

  run:fg:
    desc: Run all services in foreground
    cmds:
      - process-compose up -f process-compose.yaml

  stop:
    desc: Stop all services
    cmds:
      - process-compose down

  test:
    desc: Run tests for all subsystems
    cmds:
      - task nats:test
      - task liftbridge:test
      - task arc:test
      - task telegraf:test

  deps:
    desc: Download dependencies for all subsystems
    cmds:
      - task nats:deps
      - task liftbridge:deps
      - task arc:deps
      - task telegraf:deps

  clean:
    desc: Clean all build artifacts
    cmds:
      - task nats:clean
      - task liftbridge:clean
      - task arc:clean
      - task telegraf:clean
      - task grafana:clean

  clean:data:
    desc: Clean all data directories
    cmds:
      - task nats:clean:data
      - task liftbridge:clean:data
      - task arc:clean:data
      - task telegraf:clean:data
      - task grafana:clean:data

  clean:src:
    desc: Clean all source directories
    cmds:
      - task nats:clean:src
      - task liftbridge:clean:src
      - task arc:clean:src
      - task telegraf:clean:src
      - task grafana:clean:src

  clean:all:
    desc: Clean everything (.src, .bin, .data)
    cmds:
      - task nats:clean:all
      - task liftbridge:clean:all
      - task arc:clean:all
      - task telegraf:clean:all
      - task grafana:clean:all

  install:deps:
    desc: Install required tools (hugo, gh, process-compose)
    cmds:
      - |
        if ! command -v hugo &> /dev/null; then
          echo "Installing hugo..."
          {{if eq OS "darwin"}}brew install hugo{{else}}go install github.com/gohugoio/hugo@latest{{end}}
        fi
      - |
        if ! command -v gh &> /dev/null; then
          echo "Installing gh..."
          {{if eq OS "darwin"}}brew install gh{{else}}go install github.com/cli/cli/v2/cmd/gh@latest{{end}}
        fi
      - |
        if ! command -v process-compose &> /dev/null; then
          echo "Installing process-compose..."
          {{if eq OS "darwin"}}brew install process-compose{{else}}go install github.com/F1bonacc1/process-compose@latest{{end}}
        fi
    status:
      - command -v hugo
      - command -v gh
      - command -v process-compose

  docs:dev:
    desc: Run Hugo dev server
    dir: docs
    cmds:
      - hugo server -D

  docs:build:
    desc: Build Hugo site
    dir: docs
    cmds:
      - hugo --minify
