version: '3'

vars:
  GH_UPSTREAM_REPO: https://github.com/cli/cli.git
  GH_VERSION: '{{.GH_VERSION | default "v2.83.2"}}'
  GH_SRC: '{{.TASKFILE_DIR}}/.src'
  GH_BIN: '{{.TASKFILE_DIR}}/.bin'
  GH_DATA: '{{.TASKFILE_DIR}}/.data'

env:
  GOWORK: off

tasks:
  # src: tasks
  src:clone:
    desc: Clone the upstream repository at pinned version
    cmds:
      - git clone --branch {{.GH_VERSION}} --depth 1 {{.GH_UPSTREAM_REPO}} {{.GH_SRC}}
    status:
      - test -d {{.GH_SRC}}

  src:update:
    desc: Fetch and checkout pinned version
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    cmds:
      - git fetch --tags
      - git checkout {{.GH_VERSION}}

  # bin: tasks
  bin:build:
    desc: Build gh binary
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    status:
      - test -f {{.GH_BIN}}/gh
    cmds:
      - mkdir -p {{.GH_BIN}}
      - make build
      - cp bin/gh {{.GH_BIN}}/

  bin:download:
    desc: Download pre-built binary from release
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - mkdir -p {{.GH_BIN}}
      - curl -L https://github.com/{{.RELEASE_REPO}}/releases/{{.RELEASE_VERSION}}/download/gh-{{.GOOS}}-{{.GOARCH}}.tar.gz | tar xz -C {{.GH_BIN}}
      - echo "{{.RELEASE_VERSION}}" > {{.GH_BIN}}/.version
    status:
      - test -f {{.GH_BIN}}/gh

  # dev: tasks
  dev:run:
    desc: Run gh from source (development mode)
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    cmds:
      - mkdir -p {{.GH_DATA}}
      - go run ./cmd/gh {{.CLI_ARGS}}

  # Service tasks
  deps:
    desc: Download dependencies
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    cmds:
      - go mod download
    status:
      - test -d {{.GH_SRC}}/vendor || go list -m all >/dev/null 2>&1

  ensure:
    desc: Ensure binary exists (build or download)
    status:
      - test -f {{.GH_BIN}}/gh
    cmds:
      - task: bin:download

  install:
    desc: Install gh binary
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    cmds:
      - go install ./cmd/gh

  test:
    desc: Run tests
    deps: [src:clone]
    dir: '{{.GH_SRC}}'
    cmds:
      - go test -v ./...

  package:
    desc: Package binary for release
    vars:
      GOOS: '{{.GOOS | default OS}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
      DIST: '{{.DIST | default .DIST_DIR}}'
      BINARY_NAME: gh
    cmds:
      - tar -czvf {{.DIST}}/{{.BINARY_NAME}}-{{.GOOS}}-{{.GOARCH}}.tar.gz -C {{.GH_BIN}} {{.BINARY_NAME}}

  # clean: tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.GH_BIN}}
    status:
      - '! test -d {{.GH_BIN}}'

  clean:all:
    desc: Clean everything (.src, .bin, .data)
    cmds:
      - rm -rf {{.GH_SRC}} {{.GH_BIN}} {{.GH_DATA}}

  clean:data:
    desc: Clean data directory
    cmds:
      - rm -rf {{.GH_DATA}}
    status:
      - '! test -d {{.GH_DATA}}'

  clean:src:
    desc: Clean source directory
    cmds:
      - rm -rf {{.GH_SRC}}
    status:
      - '! test -d {{.GH_SRC}}'
