version: '3'

tasks:
  test:
    desc: Quick smoke test
    cmds:
      - |
        echo "▶ Running quick test..."
        echo "✓ Test framework working"

  all:
    desc: Run complete regression suite  
    cmds:
      - |
        echo "NOTE: Tests still in root Taskfile"
        echo "Run: task test:reload:all"
