version: '3'

vars:
  LB_UPSTREAM_REPO: https://github.com/Basekick-Labs/liftbridge.git
  LB_VERSION: '{{.LB_VERSION | default "master"}}'
  LB_SRC: '{{.TASKFILE_DIR}}/.src'
  LB_BIN: '{{.TASKFILE_DIR}}/.bin'
  LB_DATA: '{{.TASKFILE_DIR}}/.data'
  LB_RELEASE_URL: https://github.com/{{.RELEASE_REPO}}/releases/{{.RELEASE_VERSION}}/download

env:
  GOWORK: off

tasks:
  # src: tasks
  src:clone:
    desc: Clone the upstream repository at pinned version
    cmds:
      - git clone --branch {{.LB_VERSION}} --depth 1 {{.LB_UPSTREAM_REPO}} {{.LB_SRC}}
    status:
      - test -d {{.LB_SRC}}

  src:update:
    desc: Fetch and checkout pinned version
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    cmds:
      - git fetch --tags
      - git checkout {{.LB_VERSION}}

  # bin: tasks
  bin:build:
    desc: Build liftbridge server
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    status:
      - test -f {{.LB_BIN}}/liftbridge
    cmds:
      - mkdir -p {{.LB_BIN}}
      - go build -o {{.LB_BIN}}/liftbridge .

  bin:download:
    desc: Download pre-built binary from release
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - mkdir -p {{.LB_BIN}}
      - curl -L {{.LB_RELEASE_URL}}/liftbridge-{{.GOOS}}-{{.GOARCH}}.tar.gz | tar xz -C {{.LB_BIN}}
      - echo "{{.RELEASE_VERSION}}" > {{.LB_BIN}}/.version
    status:
      - test -f {{.LB_BIN}}/liftbridge

  # dev: tasks
  dev:run:
    desc: Run liftbridge from source (development mode)
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    cmds:
      - mkdir -p {{.LB_DATA}}
      - go run . --data-dir={{.LB_DATA}}

  # Service tasks
  deps:
    desc: Download dependencies
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    cmds:
      - go mod download
    status:
      - test -d {{.LB_SRC}}/vendor || go list -m all >/dev/null 2>&1

  ensure:
    desc: Ensure binary exists (build or download)
    status:
      - test -f {{.LB_BIN}}/liftbridge
    cmds:
      - task: bin:download

  health:
    desc: Check if Liftbridge is healthy
    cmds:
      - nc -z localhost 9292

  install:
    desc: Install liftbridge binary
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    cmds:
      - go install .

  run:
    desc: Run liftbridge binary
    deps: [ensure]
    cmds:
      - mkdir -p {{.LB_DATA}}
      - '{{.LB_BIN}}/liftbridge --data-dir={{.LB_DATA}}'

  test:
    desc: Run tests
    deps: [src:clone]
    dir: '{{.LB_SRC}}'
    cmds:
      - go test -v ./...

  package:
    desc: Package binary for release
    vars:
      GOOS: '{{.GOOS | default OS}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
      DIST: '{{.DIST | default .DIST_DIR}}'
      BINARY_NAME: liftbridge
    cmds:
      - tar -czvf {{.DIST}}/{{.BINARY_NAME}}-{{.GOOS}}-{{.GOARCH}}.tar.gz -C {{.LB_BIN}} {{.BINARY_NAME}}

  # clean: tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.LB_BIN}}
    status:
      - '! test -d {{.LB_BIN}}'

  clean:all:
    desc: Clean everything (.src, .bin, .data)
    cmds:
      - rm -rf {{.LB_SRC}} {{.LB_BIN}} {{.LB_DATA}}

  clean:data:
    desc: Clean data directory
    cmds:
      - rm -rf {{.LB_DATA}}
    status:
      - '! test -d {{.LB_DATA}}'

  clean:src:
    desc: Clean source directory
    cmds:
      - rm -rf {{.LB_SRC}}
    status:
      - '! test -d {{.LB_SRC}}'
