version: '3'

vars:
  PC_BIN_NAME: process-compose
  PC_UPSTREAM_REPO: https://github.com/F1bonacc1/process-compose.git
  PC_VERSION: '{{.PC_VERSION | default "v1.85.0"}}'
  PC_SRC: '{{.TASKFILE_DIR}}/.src'
  PC_BIN: '{{.TASKFILE_DIR}}/.bin'
  PC_BIN_PATH: '{{.PC_BIN}}/{{.PC_BIN_NAME}}'
  PC_DATA: '{{.TASKFILE_DIR}}/.data'
  _PC_SOCKET_DEFAULT: '{{.TASKFILE_DIR}}/.pc.sock'
  PC_SOCKET: '{{.PC_SOCKET | default ._PC_SOCKET_DEFAULT}}'
  _PC_CONFIG_DEFAULT: '{{.ROOT_DIR}}/process-compose.yaml'
  PC_CONFIG: '{{.PC_CONFIG | default ._PC_CONFIG_DEFAULT}}'

env:
  GOWORK: off

tasks:
  # src: tasks
  src:clone:
    desc: Clone the upstream repository at pinned version
    cmds:
      - git clone --branch {{.PC_VERSION}} --depth 1 {{.PC_UPSTREAM_REPO}} {{.PC_SRC}}
    status:
      - test -d {{.PC_SRC}}

  src:update:
    desc: Fetch and checkout pinned version
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    cmds:
      - git fetch --tags
      - git checkout {{.PC_VERSION}}

  # bin: tasks
  bin:build:
    desc: Build process-compose binary
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    status:
      - test -f {{.PC_BIN_PATH}}
    cmds:
      - mkdir -p {{.PC_BIN}}
      - go build -o {{.PC_BIN_PATH}} .
      - |
        {
          echo "commit: $(git -C {{.PC_SRC}} rev-parse --short HEAD 2>/dev/null || echo 'unknown')"
          echo "timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "checksum: $(shasum -a 256 {{.PC_BIN_PATH}} | awk '{print $1}')"
        } > {{.PC_BIN}}/.version

  bin:download:
    desc: Download pre-built binary from release
    vars:
      GOOS:
        sh: go env GOOS
      GOARCH:
        sh: go env GOARCH
    cmds:
      - mkdir -p {{.PC_BIN}}
      - curl -L https://github.com/F1bonacc1/process-compose/releases/download/{{.PC_VERSION}}/{{.PC_BIN_NAME}}_{{.GOOS}}_{{.GOARCH}}.tar.gz | tar xz -C {{.PC_BIN}}
      - |
        {
          echo "version: {{.PC_VERSION}}"
          echo "timestamp: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          echo "checksum: $(shasum -a 256 {{.PC_BIN_PATH}} | awk '{print $1}')"
        } > {{.PC_BIN}}/.version
    status:
      - test -f {{.PC_BIN_PATH}}

  # dev: tasks
  dev:run:
    desc: Run process-compose from source (development mode)
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    cmds:
      - mkdir -p {{.PC_DATA}}
      - go run . up -U -u {{.PC_SOCKET}} -f {{.PC_CONFIG}} -t=false

  # Service tasks
  config:version:
    desc: Output pinned version
    cmds:
      - echo "{{.PC_VERSION}}"
    silent: true

  attach:
    desc: Attach to running Process Compose instance (requires real TTY)
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    cmds:
      - '{{.PC_BIN_PATH}} attach -U -u {{.PC_SOCKET}}'

  deps:
    desc: Download dependencies
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    cmds:
      - go mod download
    status:
      - test -d {{.PC_SRC}}/vendor || go list -m all >/dev/null 2>&1

  ensure:
    desc: Ensure binary exists (build from source)
    status:
      - test -f {{.PC_BIN_PATH}}
    cmds:
      - task: bin:build

  install:
    desc: Install process-compose binary
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    cmds:
      - go install .

  "logs":
    desc: "Tail logs for a process (usage: task pc:logs PROC=nats)"
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    vars:
      PROC: '{{.PROC | default "nats"}}'
    cmds:
      - '{{.PC_BIN_PATH}} process logs {{.PROC}} -f -U -u {{.PC_SOCKET}}'

  run:
    desc: Run all services with Process Compose (TUI mode)
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    cmds:
      - mkdir -p {{.PC_DATA}}
      - '{{.PC_BIN_PATH}} up -U -u {{.PC_SOCKET}} -f {{.PC_CONFIG}}'

  run:fg:
    desc: Run all services in foreground (no TUI)
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    cmds:
      - mkdir -p {{.PC_DATA}}
      - '{{.PC_BIN_PATH}} up -U -u {{.PC_SOCKET}} -f {{.PC_CONFIG}} -t=false'

  "status":
    desc: Show status of all processes
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    cmds:
      - '{{.PC_BIN_PATH}} process list -U -u {{.PC_SOCKET}}'

  stop:
    desc: Stop all services
    dir: '{{.ROOT_DIR}}'
    deps: [ensure]
    cmds:
      - '{{.PC_BIN_PATH}} down -U -u {{.PC_SOCKET}}'

  test:
    desc: Run tests
    deps: [src:clone]
    dir: '{{.PC_SRC}}'
    cmds:
      - go test -v ./...

  package:
    desc: Package binary for release
    vars:
      GOOS: '{{.GOOS | default OS}}'
      GOARCH: '{{.GOARCH | default ARCH}}'
      DIST: '{{.DIST | default .DIST_DIR}}'
    cmds:
      - tar -czvf {{.DIST}}/{{.PC_BIN_NAME}}-{{.GOOS}}-{{.GOARCH}}.tar.gz -C {{.PC_BIN}} {{.PC_BIN_NAME}}

  # clean: tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.PC_BIN}}
      - rm -f {{.PC_SOCKET}}
    status:
      - '! test -d {{.PC_BIN}}'

  clean:all:
    desc: Clean everything (.src, .bin, .data, socket)
    cmds:
      - rm -rf {{.PC_SRC}} {{.PC_BIN}} {{.PC_DATA}} {{.PC_SOCKET}}

  clean:data:
    desc: Clean data directory
    cmds:
      - rm -rf {{.PC_DATA}}
    status:
      - '! test -d {{.PC_DATA}}'

  clean:src:
    desc: Clean source directory
    cmds:
      - rm -rf {{.PC_SRC}}
    status:
      - '! test -d {{.PC_SRC}}'
