version: '3'

vars:
  PC_SOCKET: '{{.TASKFILE_DIR}}/../.pc.sock'
  PC_CONFIG: '{{.TASKFILE_DIR}}/../process-compose.yaml'

tasks:
  ensure:
    desc: Ensure process-compose is installed
    status:
      - command -v process-compose
    cmds:
      - |
        {{if eq OS "darwin"}}
        brew install process-compose
        {{else}}
        go install github.com/F1bonacc1/process-compose@latest
        {{end}}

  run:
    desc: Run all services with Process Compose (TUI mode)
    deps: [ensure]
    cmds:
      - process-compose up -U -u {{.PC_SOCKET}} -f {{.PC_CONFIG}}

  run:fg:
    desc: Run all services in foreground (no TUI)
    deps: [ensure]
    cmds:
      - process-compose up -U -u {{.PC_SOCKET}} -f {{.PC_CONFIG}} -t=false

  attach:
    desc: Attach to running Process Compose instance (requires real TTY)
    deps: [ensure]
    cmds:
      - process-compose attach -U -u {{.PC_SOCKET}}

  "logs":
    desc: "Tail logs for a process (usage: task pc:logs PROC=nats)"
    deps: [ensure]
    vars:
      PROC: '{{.PROC | default "nats"}}'
    cmds:
      - process-compose process logs {{.PROC}} -f -U -u {{.PC_SOCKET}}

  "status":
    desc: Show status of all processes
    deps: [ensure]
    cmds:
      - process-compose process list -U -u {{.PC_SOCKET}}

  stop:
    desc: Stop all services
    deps: [ensure]
    cmds:
      - process-compose down -U -u {{.PC_SOCKET}}

  clean:
    desc: Clean socket file
    cmds:
      - rm -f {{.PC_SOCKET}}
    status:
      - '! test -f {{.PC_SOCKET}}'

  clean:data:
    desc: No data directory for process-compose
    cmds:
      - echo "Process Compose has no data directory"

  clean:src:
    desc: No source directory for process-compose
    cmds:
      - echo "Process Compose has no source directory"

  clean:all:
    desc: Clean everything (socket)
    cmds:
      - rm -f {{.PC_SOCKET}}

  bin:download:
    desc: Process Compose is a system tool (no-op)
    status:
      - command -v process-compose
    cmds:
      - echo "Process Compose is installed via system package manager or go install"

  src:clone:
    desc: Process Compose has no source (no-op)
    cmds:
      - echo "Process Compose has no source to clone"

  src:update:
    desc: Process Compose has no source (no-op)
    cmds:
      - echo "Process Compose has no source to update"

  build:
    desc: Process Compose has no build step (no-op)
    cmds:
      - echo "Process Compose has no build step"

  test:
    desc: No tests for process-compose orchestration
    cmds:
      - echo "No tests for Process Compose orchestration"

  deps:
    desc: No dependencies for process-compose
    cmds:
      - echo "Process Compose has no dependencies"
