version: '3'

vars:
  DOCS_VERSION: 'latest'
  DOCS_SRC: '{{.TASKFILE_DIR}}'
  DOCS_BIN: '{{.TASKFILE_DIR}}/.bin'
  DOCS_DATA: '{{.TASKFILE_DIR}}/.data'
  DOCS_PORT: '1313'

tasks:
  # src: tasks
  src:clone:
    desc: Docs source is in git (no-op)
    status:
      - test -d {{.DOCS_SRC}}/content
    cmds:
      - echo "Docs source is in git, nothing to clone"

  src:update:
    desc: Update docs source (no-op, use git pull)
    cmds:
      - echo "Use git pull to update docs source"

  # bin: tasks
  bin:build:
    desc: Build Hugo site
    dir: '{{.DOCS_SRC}}'
    deps: [ensure]
    sources:
      - '{{.DOCS_SRC}}/content/**/*'
      - '{{.DOCS_SRC}}/layouts/**/*'
      - '{{.DOCS_SRC}}/static/**/*'
      - '{{.DOCS_SRC}}/hugo.toml'
    generates:
      - '{{.DOCS_BIN}}/**/*'
    cmds:
      - hugo --minify -d {{.DOCS_BIN}}

  bin:download:
    desc: Hugo is a system tool (no-op)
    status:
      - command -v hugo
    cmds:
      - echo "Hugo is installed via system package manager"

  # Service tasks
  deps:
    desc: No dependencies for Hugo docs
    cmds:
      - echo "Hugo docs have no dependencies"

  ensure:
    desc: Ensure Hugo is installed (installs via go if missing)
    status:
      - command -v hugo
    cmds:
      - go install github.com/gohugoio/hugo@latest

  health:
    desc: Check if Hugo server is healthy
    cmds:
      - curl -sf http://localhost:1313/plat-telemetry/ > /dev/null

  "new":
    desc: "Create new content (usage: task docs:new PAGE=architecture/new-page)"
    vars:
      PAGE: '{{.PAGE | default "posts/new-post"}}'
    dir: '{{.DOCS_SRC}}'
    cmds:
      - hugo new content/{{.PAGE}}.md

  run:
    desc: Run Hugo dev server (long-running service with hot reload)
    dir: '{{.DOCS_SRC}}'
    deps: [ensure]
    cmds:
      - hugo server -D --bind 0.0.0.0 --port {{.DOCS_PORT}}

  test:
    desc: Check Hugo build works
    dir: '{{.DOCS_SRC}}'
    cmds:
      - hugo --minify -d {{.DOCS_BIN}}

  # clean: tasks
  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf {{.DOCS_BIN}}
    status:
      - '! test -d {{.DOCS_BIN}}'

  clean:all:
    desc: Clean everything (.bin, .data)
    cmds:
      - rm -rf {{.DOCS_BIN}} {{.DOCS_DATA}} {{.DOCS_SRC}}/.hugo_build.lock

  clean:data:
    desc: Clean data directory
    cmds:
      - rm -rf {{.DOCS_DATA}}
    status:
      - '! test -d {{.DOCS_DATA}}'

  clean:src:
    desc: Clean source directory (no-op, source is in git)
    cmds:
      - echo "Docs source is in git, not .src/"
